"""add verify code fields

Revision ID: 57f45a4b6b09
Revises: afa74dd44bea
Create Date: 2026-03-26 10:49:23.475901

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '57f45a4b6b09'
down_revision = 'afa74dd44bea'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_code', sa.String(length=4), nullable=True))
        batch_op.add_column(sa.Column('verify_code_exp', sa.DateTime(timezone=True), nullable=True))
        batch_op.drop_column('verify_token')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('verify_token', sa.VARCHAR(length=255), autoincrement=False, nullable=True))
        batch_op.drop_column('verify_code_exp')
        batch_op.drop_column('verify_code')

    # ### end Alembic commands ###
