"""add seller fields to user

Revision ID: eba4887b2845
Revises: 57f45a4b6b09
Create Date: 2026-03-29 09:44:45.561402

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eba4887b2845'
down_revision = '57f45a4b6b09'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('seller_name', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seller_nip', sa.String(length=20), nullable=True))
        batch_op.add_column(sa.Column('seller_address', sa.String(length=500), nullable=True))
        batch_op.add_column(sa.Column('seller_email', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('seller_bank', sa.String(length=50), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('seller_bank')
        batch_op.drop_column('seller_email')
        batch_op.drop_column('seller_address')
        batch_op.drop_column('seller_nip')
        batch_op.drop_column('seller_name')

    # ### end Alembic commands ###
